@extends('layouts.global')
@section('content')
@include('components.navigation_bar_admin')
@include('components.promo_ads')
@include('components.top_product')
@include('components.about_us')
@include('components.review')
@include('components.footer')
@endSection
